### ISSUE TITLE
i have a question in this challenge

### ISSUE THREAD

**Issue by MennaShaaban** [Ahmedwaleed22/The-Dark-Lord#1]
when i try to encode your code 
![image](https://user-images.githubusercontent.com/73165636/188009411-e20ca507-2567-47de-bc21-b4237a9518b2.png)
on this site 
https://www.base64decode.org/
i get different result 
```PD9waHAKCmNsYXNzIFVzZXIKewogICAgcHJpdmF0ZSAkcm9sZSA9ICJWb2xkZW1vcnQiOwoKICAgIHB1YmxpYyBmdW5jdGlvbiBHZXRJbmZvKCkKICAgIHsKICAgICAgICBpbmNsdWRlKCJ0aXRsZXMucGhwIik7CgogICAgICAgIGlmKCR0aGlzLT5yb2xlID09PSAiVm9sZGVtb3J0IikKICAgICAgICB7CiAgICAgICAgICAgIHJldHVybiAkVGl0bGVfQTsKICAgICAgICB9CiAgICAgICAgZWxzZQogICAgICAgIHsKICAgICAgICAgICAgcmV0dXJuICRUaXRsZV9COwogICAgICAgIH0KICAgIH0KCn0KCiR1c2VyID0gbmV3IFVzZXIoKTsKCiRzb2x1dGlvbiA9IGJhc2U2NF9lbmNvZGUoc2VyaWFsaXplKCR1c2VyKSk7CgplY2hvICRzb2x1dGlvbjs=```
and i don't get the flag
any help here, plz?

**Comment by Ahmedwaleed22** [comment]
Hello Menna,
Please just run the PHP code it will return the serialized and base64 encoded text that you have to use don't encode the whole code but just run the code and you will get the right output.
